# Architecture Overview

This section contains the C4 architecture diagrams for **{{PROJECT_NAME}}**.

## C4 Model

The [C4 model](https://c4model.com/) provides a hierarchical way to visualize software architecture:

| Level | Diagram | Audience | Focus |
|-------|---------|----------|-------|
| 1 | [Context](c4-context.md) | Everyone | System + external actors |
| 2 | [Container](c4-container.md) | Technical | Apps, DBs, services |
| 3 | [Component](c4-component.md) | Developers | Internal modules |

## Diagram Legend

```mermaid
C4Context
    Person(person, "Person", "A user or external actor")
    System(system, "System", "The main system")
    System_Ext(external, "External System", "Third-party service")
    SystemDb(database, "Database", "Data storage")

    Rel(person, system, "Uses")
    Rel(system, external, "Calls API")
    Rel(system, database, "Reads/Writes")
```

## Regenerating Diagrams

To regenerate the architecture diagrams:

```bash
/c4                    # Generate all diagrams
/c4 --context          # Context diagram only
/c4 --container        # Container diagram only
/c4 --component        # Component diagram only
/c4 --incremental      # Update without overwriting manual edits
```

## Manual Edits

To preserve manual edits when regenerating, add this comment to any section:

```markdown
<!-- MANUAL -->
Your manually edited content here.
<!-- /MANUAL -->
```

---

*Generated by `/c4` skill. Last updated: {{GENERATED_DATE}}*
