#!/bin/bash
# ============================================================================
# git-guard.test.sh - Tests for git-guard.sh hook
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/test-utils.sh"

HOOK="$HOME/.claude/scripts/git-guard.sh"

echo "Testing: git-guard.sh"
echo "───────────────────────────────────────────────"

# === Fast exit (non-git commands) ===
test_hook "Pass through non-git commands" \
    "$HOOK" \
    "$(make_bash_input 'npm install')" \
    0

test_hook "Pass through git status" \
    "$HOOK" \
    "$(make_bash_input 'git status')" \
    0

test_hook "Pass through git diff" \
    "$HOOK" \
    "$(make_bash_input 'git diff')" \
    0

test_hook "Pass through non-Bash tools" \
    "$HOOK" \
    "$(make_tool_input 'Read')" \
    0

test_hook "Handle empty input" \
    "$HOOK" \
    "" \
    0

# === AI mention blocking ===
test_hook "Block Co-Authored-By: Claude" \
    "$HOOK" \
    "$(make_bash_input "git commit -m 'feat: add auth\n\nCo-Authored-By: Claude <noreply@anthropic.com>'")" \
    2 \
    "COMMIT BLOCKED"

test_hook "Block generated by AI" \
    "$HOOK" \
    "$(make_bash_input "git commit -m 'feat: generated by AI'")" \
    2 \
    "COMMIT BLOCKED"

test_hook "Block ai-assisted" \
    "$HOOK" \
    "$(make_bash_input "git commit -m 'feat: ai-assisted refactor'")" \
    2 \
    "COMMIT BLOCKED"

test_hook "Block chatgpt mention" \
    "$HOOK" \
    "$(make_bash_input "git commit -m 'feat: chatgpt helped'")" \
    2 \
    "COMMIT BLOCKED"

test_hook "Block anthropic mention" \
    "$HOOK" \
    "$(make_bash_input "git commit -m 'chore: anthropic integration'")" \
    2 \
    "COMMIT BLOCKED"

test_hook "Allow clean commit message" \
    "$HOOK" \
    "$(make_bash_input "git commit -m 'feat: add user authentication'")" \
    0

test_hook "Allow commit with --message= flag" \
    "$HOOK" \
    "$(make_bash_input "git commit --message='fix: resolve login bug'")" \
    0

# === Force push correction ===
test_hook_stdout "Auto-correct --force to --force-with-lease" \
    "$HOOK" \
    "$(make_bash_input 'git push --force origin main')" \
    0 \
    "force-with-lease"

test_hook "Allow --force-with-lease (no correction needed)" \
    "$HOOK" \
    "$(make_bash_input 'git push --force-with-lease origin main')" \
    0

test_hook "Allow normal push" \
    "$HOOK" \
    "$(make_bash_input 'git push origin feature/test')" \
    0

# === RTK normalization ===
test_hook "Handle rtk-prefixed git commands" \
    "$HOOK" \
    "$(make_bash_input 'rtk git status')" \
    0

test_hook "Handle rtk proxy git commands" \
    "$HOOK" \
    "$(make_bash_input 'rtk proxy git status')" \
    0

# === HEREDOC commit message ===
HEREDOC_INPUT=$(cat <<'TESTJSON'
{"tool_name":"Bash","tool_input":{"command":"git commit -m \"$(cat <<'EOF'\nfeat: add feature\n\nCo-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>\nEOF\n)\""}}
TESTJSON
)
test_hook "Block AI mention in HEREDOC commit" \
    "$HOOK" \
    "$HEREDOC_INPUT" \
    2 \
    "COMMIT BLOCKED"

# === Summary ===
print_summary "git-guard.sh"
exit $?
