#!/usr/bin/env bats
# Tests for git-guard.sh (PreToolUse Bash hook)

SCRIPT=""

setup() {
    load '../helpers/setup'
    load '../helpers/mocks'
    common_setup
    SCRIPT="$SCRIPTS_DIR/git-guard.sh"
}

teardown() {
    common_teardown
}

# Helper: run git-guard with mock input
run_guard() {
    local tool_name="${1:-Bash}"
    local command="${2:-}"
    local json
    json=$(mock_hook_input "$tool_name" "$command")
    run bash -c 'echo "$1" | bash "$2"' -- "$json" "$SCRIPT"
}

# --- AI mention blocking ---

@test "blocks commit with Co-Authored-By: Claude" {
    run_guard "Bash" "git commit -m 'feat: add feature

Co-Authored-By: Claude <noreply@anthropic.com>'"
    [ "$status" -eq 2 ]
}

@test "blocks commit with Generated by AI (case-insensitive)" {
    run_guard "Bash" "git commit -m 'Generated by AI assistant'"
    [ "$status" -eq 2 ]
}

@test "allows clean commit message" {
    run_guard "Bash" "git commit -m 'feat: add user authentication'"
    [ "$status" -eq 0 ]
}

# --- Force push protection ---

@test "rewrites --force to --force-with-lease on push" {
    run_guard "Bash" "git push origin main --force"
    [ "$status" -eq 0 ]
    # Output should contain the hookSpecificOutput JSON with updatedInput
    echo "$output" | grep -q "force-with-lease"
}

# --- Non-git fast path ---

@test "allows non-git commands (fast path exit)" {
    run_guard "Bash" "ls -la /tmp"
    [ "$status" -eq 0 ]
}

@test "skips non-Bash tools" {
    run_guard "Write" "anything"
    [ "$status" -eq 0 ]
}

# --- Secret patterns (requires git environment) ---

@test "detects hardcoded GitHub PAT pattern in staged content" {
    # Set up a minimal git repo for staging
    local repo="$TEST_TMPDIR/repo"
    mkdir -p "$repo"
    cd "$repo"
    git init -q
    git config user.email "test@test.com"
    git config user.name "Test"

    # Create an initial commit so HEAD exists
    echo "init" > init.txt
    git add init.txt
    git commit -q -m "init"

    # Stage a file with a GitHub PAT (constructed dynamically to avoid GitGuardian)
    echo "TOKEN=$(fake_github_pat)" > secret.txt
    git add secret.txt

    # Run git-guard as a commit command
    local json
    json=$(mock_hook_input "Bash" "git commit -m 'add config'")
    run bash -c 'echo "$1" | bash "$2"' -- "$json" "$SCRIPT"
    [ "$status" -eq 2 ]
}

@test "detects AWS access key pattern in staged content" {
    local repo="$TEST_TMPDIR/repo"
    mkdir -p "$repo"
    cd "$repo"
    git init -q
    git config user.email "test@test.com"
    git config user.name "Test"

    echo "init" > init.txt
    git add init.txt
    git commit -q -m "init"

    echo "AWS_KEY=$(fake_aws_key)" > creds.txt
    git add creds.txt

    local json
    json=$(mock_hook_input "Bash" "git commit -m 'add creds'")
    run bash -c 'echo "$1" | bash "$2"' -- "$json" "$SCRIPT"
    [ "$status" -eq 2 ]
}

@test "skips scripts in nested .claude/scripts/ for secret scan" {
    local repo="$TEST_TMPDIR/repo"
    # Use a nested path so the case pattern */.claude/scripts/* matches
    mkdir -p "$repo/home/user/.claude/scripts"
    cd "$repo"
    git init -q
    git config user.email "test@test.com"
    git config user.name "Test"

    echo "init" > init.txt
    git add init.txt
    git commit -q -m "init"

    # A script in a nested .claude/scripts/ path should be skipped
    echo "$(fake_github_pat)" > home/user/.claude/scripts/hook.sh
    git add home/user/.claude/scripts/hook.sh

    local json
    json=$(mock_hook_input "Bash" "git commit -m 'update hooks'")
    run bash -c 'echo "$1" | bash "$2"' -- "$json" "$SCRIPT"
    [ "$status" -eq 0 ]
}
